#Requires AutoHotkey v2.0

:?C*:\alf::α
:?C*:\apa::{U+2208}
:?C*:\bet::ß
:?C*:\com::{U+2218} 
:?C*:\con::≡
:?C*:\csi::χ
:?C*:\Del::Δ
:?C*:\del::δ
:?C*:\eps::ε
:?C*:\ex::{U+2203}
:?C*:\Fi::Φ
:?C*:\fi::φ
:?C*:\Gam::Γ
:?C*:\gam::γ
:?C*:\grad::°
:?C*:\impartit::÷
:?C*:\include::{U+2283}
:?C*:\inclus::{U+2282}
:?C*:\inf::∞
:?C*:\int::∩
:?C*:\iota::ι
:?C*:\Lam::Λ
:?C*:\lam::λ
:?C*:\mareeg::≥
:?C*:\miceg::≤
:?C*:\miu::µ
:?C*:\niu::η
:?C*:\nuapa::{U+2209}
:?C*:\nuex::{U+2204}
:?C*:\Ome::Ω
:?C*:\ome::ω
:?C*:\ori::·
:?C*:\Pi::Π
:?C*:\pi::π
:?C*:\plumin::±
:?C*:\Psi::Ψ
:?C*:\psi::ψ
:?C*:\ro::ρ
:?C*:\reunit::∪
:?C*:\Sig::Σ
:?C*:\sig::σ
:?C*:\tau::τ
:?C*:\Tet::Θ
:?C*:\tet::θ
:?C*:\upsilon::υ	
:?C*:\Xi::Ξ
:?C*:\xi::ξ
:?C*:\zet::ζ
